---
version: 2
updates:
  - package-ecosystem: gomod
    directories:
      - /ftp
      - /irc
      - /sftp
      - /torrent
    schedule:
      interval: weekly
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
