package ftp

// Standard FTP control commands. The argument column is informative
// only; not every command takes the same argument shape, see the
// individual RFCs for details.
const (
	CmdUSER = "USER"
	CmdPASS = "PASS"
	CmdACCT = "ACCT"
	CmdCWD  = "CWD"
	CmdCDUP = "CDUP"
	CmdSMNT = "SMNT"
	CmdQUIT = "QUIT"
	CmdREIN = "REIN"
	CmdPORT = "PORT"
	CmdPASV = "PASV"
	CmdTYPE = "TYPE"
	CmdSTRU = "STRU"
	CmdMODE = "MODE"
	CmdRETR = "RETR"
	CmdSTOR = "STOR"
	CmdSTOU = "STOU"
	CmdAPPE = "APPE"
	CmdALLO = "ALLO"
	CmdREST = "REST"
	CmdRNFR = "RNFR"
	CmdRNTO = "RNTO"
	CmdABOR = "ABOR"
	CmdDELE = "DELE"
	CmdRMD  = "RMD"
	CmdMKD  = "MKD"
	CmdPWD  = "PWD"
	CmdLIST = "LIST"
	CmdNLST = "NLST"
	CmdSITE = "SITE"
	CmdSYST = "SYST"
	CmdSTAT = "STAT"
	CmdHELP = "HELP"
	CmdNOOP = "NOOP"
	CmdFEAT = "FEAT"
	CmdOPTS = "OPTS"
	CmdAUTH = "AUTH"
	CmdPBSZ = "PBSZ"
	CmdPROT = "PROT"
	CmdCCC  = "CCC"
	CmdSIZE = "SIZE"
	CmdMDTM = "MDTM"
	CmdEPSV = "EPSV"
	CmdEPRT = "EPRT"
	CmdMLSD = "MLSD"
	CmdMLST = "MLST"
)
