---
name: ci

"on":
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  actions: read
  contents: read
  packages: read
  pull-requests: read
  security-events: write

jobs:
  build-test:
    strategy:
      fail-fast: false
      matrix:
        include:
          - module: ftp
            go: "1.24"
            coverage: 0
          - module: irc
            go: "1.26.7"
            coverage: 35
          - module: sftp
            go: "1.26.0"
            coverage: 0
          - module: torrent
            go: "1.26.3"
            coverage: 80
    uses: natalie-o-perret/.github/.github/workflows/reusable-build-test-go.yml@main
    with:
      go-versions: ${{ format('["{0}"]', matrix.go) }}
      go-version-latest: ${{ matrix.go }}
      coverage-threshold: ${{ matrix.coverage }}
      working-directory: ${{ matrix.module }}
      coverage-artifact-name: coverage-${{ matrix.module }}
      cache-dependency-path: ${{ matrix.module }}/go.sum

  lint-go:
    strategy:
      fail-fast: false
      matrix:
        module: [ftp, irc, sftp, torrent]
    uses: natalie-o-perret/.github/.github/workflows/reusable-lint-files-go.yml@main
    with:
      go-version-file: ${{ matrix.module }}/go.mod
      working-directory: ${{ matrix.module }}
      cache-dependency-path: ${{ matrix.module }}/go.sum

  lint-commits:
    if: github.event_name == 'pull_request'
    uses: natalie-o-perret/.github/.github/workflows/reusable-lint-commits-conventional.yml@main
    permissions:
      pull-requests: read

  lint-json:
    uses: natalie-o-perret/.github/.github/workflows/reusable-lint-files-json.yml@main

  lint-markdown:
    uses: natalie-o-perret/.github/.github/workflows/reusable-lint-files-md.yml@main

  lint-yaml:
    uses: natalie-o-perret/.github/.github/workflows/reusable-lint-files-yaml.yml@main

  codeql:
    strategy:
      fail-fast: false
      matrix:
        module: [ftp, irc, sftp, torrent]
    uses: natalie-o-perret/.github/.github/workflows/reusable-codeql.yml@main
    with:
      language: go
      go-version-file: ${{ matrix.module }}/go.mod
      working-directory: ${{ matrix.module }}
      cache-dependency-path: ${{ matrix.module }}/go.sum
      category: ${{ format('/language:go/{0}', matrix.module) }}
